version: '3.7'

services:
  EbinaStationAPI:
    build: .
    image: ebina-station-api
    container_name: EbinaStationAPI
    ports:
      - 3456:3456
      - 1234:1234
    volumes:
      - ./project:/usr/src/app/project
    env_file:
      - .env

  EbinaSstationDB:
    image: mongo
    container_name: EbinaSstationDB
    command: mongod --port 27017
    restart: always
    env_file: db.env
    ports:
      - 27017:27017
    volumes:
      - ./mongo_db:/data/db
      - ./initdb.d:/docker-entrypoint-initdb.d
