version: '3.7'

services:
  EbinaStationKoujou:
    build: ./koujou
    image: ebina-station-api
    container_name: EbinaStationKoujou
    ports:
      - 3456:3456
      - 1234:1234
    volumes:
      - ./project:/usr/src/app/project
    env_file:
      - ./koujou/.env

  EbinaStationDB:
    image: mongo
    container_name: EbinaStationDB
    command: mongod --port 27017
    restart: always
    env_file: ./mongodb/.env
    ports:
      - 27017:27017
    volumes:
      - ./mongodb/mongo_db:/data/db
      - ./mongodb/initdb.d:/docker-entrypoint-initdb.d

  EbinaStationJinji:
    image: nginx:latest
    container_name: EbinaStationJinji
    restart: always
    depends_on:
      - "EbinaStationKoujou"
      - "EbinaStationDB"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./project/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./project/nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./project/letsencrypt:/etc/letsencrypt
      - ./html:/var/www/html
      - /etc/ssl/certs/dhparam.pem:/etc/ssl/certs/dhparam.pem

  certbot:
    image: certbot/certbot
    depends_on:
      - "EbinaStationJinji"
    volumes:
      - ./project/letsencrypt:/etc/letsencrypt
      - ./html:/var/www/html
